site_name: Tasks
pages:
- Start: index.md
- Brugerguide:
    - 'For nye brugere': nye_brugere.md
    - 'Brugergrænseflade': ui.md
    - 'Funktioner':
         - 'Kunder': kunder.md
theme: readthedocs
