site_name: Tasks
pages:
- Start: index.md
- Brugerguide:
    - 'For nye brugere': nye_brugere.md
    - 'Brugergrænseflade': ui.md
    - 'Funktioner':
         - 'Kunder': kunder.md
- About:
    - 'License': 'about/license.md'
    - 'Release Notes': 'about/release-notes.md'
theme: readthedocs
